export const locations = [
  "Tel Aviv",
];

export const areas = [
  {
    id: "1",
    name: "Tel Aviv Center",
    city: "Tel Aviv",
    apartments: 45,
  },
];

export const TelAvivLocation = {
  id: "tel-aviv",
  name: "Tel Aviv",
  coordinates: { lat: 32.0853, lng: 34.7818 },
  areas: areas.filter(area => area.city === "Tel Aviv"),
};

export const TEL_AVIV_LOCATIONS = [
  "Neve Avivim",
  "Azorei Hen",
  "Kokhav HaTzafon",
  "Ramat Aviv Aleph",
  "Ramat Aviv Gimmel",
  "Ramat Aviv HaHadasha",
  "Ne'ot Afeka",
  "Ma'oz Aviv",
  "Hadar Yosef",
  "Tzahala",
  "Revivim",
  "Tel Baruch",
  "HaTzafon HaYashan (Old North)",
  "Lev HaIr",
  "Montefiori",
  "Yehuda HaMaccabi",
  "Bavli",
  "Tzamarot Ayalon",
  "Giv'at Amal Bet",
  "Kerem HaTeimanim",
  "Neve Tzedek",
  "Shabazi",
  "Florentin",
  "Neve Sha'anan",
  "Neve Ofer",
  "Kiryat Shalom",
  "Shapira",
  "HaTikva",
  "Giv'at Herzl",
  "Abu Kabir",
  "American–German Colony",
  "Nahalat Yitzhak",
  "Bitzaron",
  "Ramat Yisrael",
  "Tel Haim",
  "Ramat HaTayasim",
  "Neve Tzahal",
  "Kfar Shalem",
  "HaArgazim",
  "Ezra",
  "Yad Eliyahu",
  "Old Jaffa",
  "Ajami",
  "Menashiya",
  "Giv'at Aliyah",
  "Tzahalon",
];